DRAFT, this is for me to compare my code to master, please wait until PR is ready - 9 implement more advanced camera controls
john-and-jaden/strategy.io pull request #29
Opened 2020-12-16 02:01 UTC by jpabadir

2020-12-20 23:55 UTC, JadenBalogh requested changes
Overall the changes feel good so far - this camera controller is really coming along! It actually feels really satisfying to use now, and we're just a few changes away from a completed product.

There are a few features that need to be added/updated:
 - When reversing direction (going from zooming in to zooming out or vice versa) the direction of scrolling should immediately change. Currently, there is a delay as the velocity has to go all the way from negative to positive (or vice versa). This is especially noticeable with high `scrollDampTime` and low `scrollSensitivity`.
 - If you continue trying to zoom at the extremes (fully zoomed in or out) it seems to continue to increase the velocity, which makes it take a long time to "respond" to inputs in the opposite direction. Fixing the first point should fix this issue as well depending on how it is resolved.
 - The clamping of camera position to the bounds of the world needs to apply to the edges of the camera, not the middle. The player should at most be able to view the entire map, plus some extra space in either axis depending on aspect ratio (we could also add a parameter to allow for some defined extra zoom amount beyond the normal extents). Also, zooming out from anywhere in the map should end the player with a complete centered view of the map (this should happen naturally from the first part of this change). When this is done, the `maxZoom` parameter can be removed.
 - `edgeCamMoveThreshold` should clarify that it operates in viewport units either by being renamed or given a tooltip in the inspector. It is probably more accurately described as the proportion of the screen which is considered as the edge.
 - `AddToCurrentCameraPosition(xAddition,yAddition)` can be more concisely named. For example, `MoveCamera(xDelta,yDelta)`. Also, using `+=` in this function might make the code more concise and readable.
 - Speeds should always operate in units/**second** so that humans setting the values in the inspector can understand what the values mean without needing to read through the code. `maxCameraMoveSpeed` should be changed to operate in seconds (use Time.deltaTime).
 - The Dampable class is a good idea but is a bit confusing in its current iteration. See comments and suggestions specific to that class. Also, the instances of Dampable in the CameraController script should be `private`.
 - See comments for minor naming updates and format changes.

Side note:
For some reason this PR includes a bunch of resource system changes as well. Have those already been merged into `master` from their proper PR? If not, merging this PR will merge potentially incomplete changes from another branch. I would double-check the current state of your working branches to ensure that everything is being committed as expected.

2020-12-20 23:55 UTC, JadenBalogh commented on Assets/Scripts/CameraController.cs
> +        int yFactor = mousePos.y < edgeCamMoveThreshold ? -1 : (mousePos.y > 1 - edgeCamMoveThreshold ? 1 : 0);
I would rename these to `xDir` and `yDir` or something similar to be more accurate.

2020-12-20 23:55 UTC, JadenBalogh commented on Assets/Scripts/CameraController.cs
> +        scrollMoveDampable.UpdateAndDampen(Input.GetAxis("Mouse ScrollWheel"), scrollVelocity);
Implementing the Dampable changes as I commented on that class, these lines would change to something like this:

```suggestion
        float scrollAcceleration = Input.GetAxis("Mouse ScrollWheel") * scrollSensitivity * (invertScrolling ? -1 : 1);
        scrollDampable.UpdateSpeed(scrollAcceleration);
```

2020-12-20 23:55 UTC, JadenBalogh commented on Assets/Scripts/CameraController.cs
> +        edgeMoveYDampable.UpdateAndDampen(yFactor, Mathf.Clamp(yVelocity, -maxCameraMoveSpeed, maxCameraMoveSpeed));
These lines (really the whole function) should also be greatly simplified using the Dampable updates I listed. In fact, you might want to consider building the clamping feature directly into Dampable. Maybe make the UpdateSpeed method take an optional parameter of `maxSpeed` which defaults to `Mathf.Infinity`, and apply the clamp when updating the speed field. That also makes the Dampable class more extendable for other uses in the future.

2020-12-21 10:33 UTC, jpabadir commented on Assets/Scripts/Dampable.cs
> +}
This makes a lot of sense. You're definitely right about implementing Dampable as an API all the way through - with all the logic self-contained. Thanks for even including the code in your comment, I committed it!

2020-12-21 10:55 UTC, jpabadir commented on Assets/Scripts/CameraController.cs
> +        int yFactor = mousePos.y < edgeCamMoveThreshold ? -1 : (mousePos.y > 1 - edgeCamMoveThreshold ? 1 : 0);
<img width="496" alt="Screen Shot 2020-12-21 at 11 54 48 AM" src="https://user-images.githubusercontent.com/21204917/102769712-558cce00-4383-11eb-9156-61e6cbd2bac9.png">

2020-12-21 11:51 UTC, jpabadir commented on Assets/Scripts/CameraController.cs
> +        edgeMoveYDampable.UpdateAndDampen(yFactor, Mathf.Clamp(yVelocity, -maxCameraMoveSpeed, maxCameraMoveSpeed));
Having the UpdateSpeed method take an additional parameter is definitely a way to include the clamp behaviour in the Dampable class, but what if, instead, we add a new constructor overload to that class which takes a minimum and a maximum speed? I feel like it would be cleaner, I'll try to implement it that way.

2020-12-28 05:04 UTC, JadenBalogh requested changes
Nice work! I've left a few comments for minor naming and formatting changes that I think are worth adding.

2020-12-28 05:04 UTC, JadenBalogh commented on Assets/Scripts/Game/System/CameraController.cs
> +        float zoomLevel = -(cameraHalfHeight - maxCameraHalfHeight);
This would be more readable reformulated as `maxCameraSize - cameraSize` (factoring through the negative, flipping order).

2020-12-28 07:17 UTC, jpabadir commented on Assets/Scripts/Game/System/CameraController.cs
> +        float scrollAcceleration = Input.GetAxis("Mouse ScrollWheel") * scrollSensitivity * (invertScrolling ? -1 : 1);
Sure, I can do that, but again, as per our conversation, you and I have an opposite definition of "as expected" when it comes to scrolling direction.

2020-12-28 10:39 UTC, jpabadir commented on Assets/Scripts/Game/System/CameraController.cs
> +    private int sideMargins = 10;
Instead of a tooltip, I opted for moving these fields under the panning header, and renaming `sideMargins` to `panSideMargins`.

2020-12-29 01:32 UTC, JadenBalogh requested changes
Some more comments below, including some things I forgot to mention in earlier reviews.

2020-12-29 01:32 UTC, JadenBalogh commented on Assets/Scripts/Game/System/CameraController.cs
> +        float currentMaxDistFromCenterX = (zoomLevel / maxZoomLevel) * overallMaxDistFromCenterX;
This is a fairly complex function. To clarify the meaning (and shorten some lines), I would suggest some clean-ups:

```suggestion
        // Calculate y bounds
        float cameraSize = Camera.main.orthographicSize;
        float boundY = worldHeight / 2 - cameraSize + panSideMargin;

        // Calculate zoom level
        float maxZoomLevel = maxCameraSize - minCameraSize;
        float zoomLevel = maxCameraSize - cameraSize;

        // Calculate x bounds based on zoom level
        float minCameraSizeX = minCameraSize * Camera.main.aspect;
        float maxBoundX = worldWidth / 2 - minCameraSizeX + panSideMargin;
        float boundX = (zoomLevel / maxZoomLevel) * maxBoundX;
        
        // Calculate clamped position values
        float clampedX = Mathf.Clamp(transform.position.x, -boundX, boundX);
        float clampedY = Mathf.Clamp(transform.position.y, -boundY, boundY);
```

2020-12-29 01:32 UTC, JadenBalogh commented on Assets/Scripts/Game/System/CameraController.cs
> +        transform.position = new Vector3(Mathf.Clamp(transform.position.x, -currentMaxDistFromCenterX, currentMaxDistFromCenterX), Mathf.Clamp(transform.position.y, -worldSize + cameraSize - panSideM
```suggestion
        // Clamp the camera position
        transform.position = new Vector3(clampedX, clampedY, transform.position.z);
```

2020-12-29 01:32 UTC, JadenBalogh commented on Assets/Scripts/Game/System/CameraController.cs
> +    private void MoveCamera(float xAddition, float yAddition)
I would personally rename these parameters to `xDelta` and `yDelta`, but that's a personal preference.

2020-12-31 15:15 UTC, jpabadir commented on Assets/Scripts/Game/System/CameraController.cs
> +        float currentMaxDistFromCenterX = (zoomLevel / maxZoomLevel) * overallMaxDistFromCenterX;
Committed suggestion.

2020-12-31 15:21 UTC, jpabadir commented on Assets/Scripts/Game/System/CameraController.cs
> +        transform.position = new Vector3(Mathf.Clamp(transform.position.x, -currentMaxDistFromCenterX, currentMaxDistFromCenterX), Mathf.Clamp(transform.position.y, -worldSize + cameraSize - panSideM
Committed.

2021-01-02 02:52 UTC, JadenBalogh approved these changes

2021-01-02 02:53 UTC, merged