DRAFT - Add basic fighter unit mechanics
john-and-jaden/strategy.io pull request #36
Opened 2021-01-04 17:01 UTC by jpabadir

2021-01-05 22:07 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Worker.cs
> +        assignedResource = (Resource)FindClosestInteractableInList(assignedCluster.Resources.ConvertAll(resource => (Interactable)resource));
I know this is convoluted and the many castings may make it inefficient. I am not sure whether we want this, or to just repeat (almost) the same code twice in the Worker and Fighter class. I usually like a concise codebase, but if we judge this method to be really inefficient, I'm happy to do the other way. 

I actually thought you could pass a list of subtypes into a method which takes a list of supertypes when I thought of this solution, but I don't think you can (I tried and had to add the casting).

2021-01-08 07:09 UTC, JadenBalogh requested changes
This code is pretty much perfect. I've made some minor comments but most things will be resolved with the static helper class we discussed. Overall really solid work - the requested changes should be only a few minutes of work, at which point we should just hold on merging this PR until building system is merged so we can use the updated selection logic here.

2021-01-08 07:09 UTC, JadenBalogh commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
I would try to makes lines at most 130-150 characters long, for readability. This overlap circle check and casting logic would also be a great candidate for a helper function in that helper class idea we talked about, as it's used in multiple places and bloats the code substantially.

2021-01-08 07:09 UTC, JadenBalogh commented on Assets/Scripts/Game/Entity/Resource.cs
> +        playerId = -1;
See comment about using `Awake()`.

2021-01-08 07:09 UTC, JadenBalogh commented on Assets/Scripts/Game/Entity/Unit.cs
> +    }
As discussed, this is a good candidate for a static helper class.

2021-01-08 07:09 UTC, JadenBalogh commented on Assets/Scripts/Game/Entity/Worker.cs
> +        assignedResource = (Resource)FindClosestInteractableInList(assignedCluster.Resources.ConvertAll(resource => (Interactable)resource));
As discussed, this can be solved using generics, and we should do so in a static helper class to be shared across all scripts.

2021-01-08 07:09 UTC, JadenBalogh commented on Assets/Scripts/Game/System/SelectionSystem.cs
> +    public List<Interactable> HoverTargets { get { return hoverTargets; } }
I'd rather keep these internal lists private for encapsulation, so let's change this back when the helper class is added.

2021-01-08 18:01 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        cooldownWaitForSeconds = new WaitForSeconds(attackCooldown);
Understood, thanks for the awesome explanation! Moving it now.

2021-01-08 18:17 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +                assignedEnemy.TakeDamage(damageAmount * Time.deltaTime);
Oh, right! Thanks.

2021-01-08 18:21 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Interactable.cs
> +    // public int PlayerId { get { return playerId; } set { playerId = value; } }
Because I thought it was useful to be able to set the playerId from the inspector, to test the fighters. I guess we could also have the second line and change the first one to a serialized field, to achieve this purpose, in which case we'd also have to change that when we do multiplayer (I expect this value to be set automatically when a player joins the server).

2021-01-08 18:21 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Interactable.cs
> +    // public int PlayerId { get { return playerId; } set { playerId = value; } }
Because I thought it was useful to be able to set the playerId from the inspector, to test the fighters. I guess we could also have the second line and change the first one to a serialized field, to achieve this purpose, in which case we'd also have to change that when we do multiplayer (I expect this value to be set automatically when a player joins the server).

2021-01-08 18:34 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        }
I created issue #40 to remind us to work on this. It has a link to this comment in the description, so we don't lose it. That's a good suggestion! I'm resolving the conversation for now.

2021-01-08 20:59 UTC, JadenBalogh commented on Assets/Scripts/Game/Entity/Interactable.cs
> +    // public int PlayerId { get { return playerId; } set { playerId = value; } }
Yeah, with the serialized field it will be perfect for now. I agree this will change when multiplayer is added.

2021-01-08 22:13 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
I am trying to make a helper method for this as you suggested. Except for this instance of the circle check and casting, I found this method where we may be able to use the generalized helper: 
```

    private Worker GetNearestWorker()
    {
        Worker nearestWorker = null;
        float shortestDistSqr = float.MaxValue;
        int workerCount = Physics2D.OverlapCircleNonAlloc(transform.position, attractionRadius, attractionTargets, attractionMask);
        for (int i = 0; i < workerCount; i++)
        {
            if (attractionTargets[i].TryGetComponent<Worker>(out Worker worker))
            {
                float workerDistSqr = (worker.transform.position - transform.position).sqrMagnitude;
                if (workerDistSqr < shortestDistSqr)
                {
                    nearestWorker = worker;
                    shortestDistSqr = workerDistSqr;
                }
            }
        }
        return nearestWorker;
    }

```
And then perhaps also this part of the code? 

```
Physics2D.OverlapCircle(mousePos, selectDistance, selectionFilter, overlapResults);
Interactable nearest = Helper.GetNearestInteractable(FilterInteractables(overlapResults), mousePos);
```

Were these the parts you were thinking of? I am trying to look through, but the code bloating you're referring to isn't immediately obvious to me, can you help me find it?

2021-01-08 22:35 UTC, JadenBalogh commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
Yeah, I believe those parts are the current candidates for refactoring. The primary reason I call this code bloat is because this physics + distance check is a low-level operation which bloats the readability of functionally simple code, not because it is used in many places. Of course, this functionality is likely to come up even more in the future as we add more types of enemies and structures as well.

That said, the last part you listed as a candidate is one I have been considering just simplifying to no longer check nearest anyway, so that one doesn't need to be refactored in this pass.

2021-01-08 22:38 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
Sounds good. I'll try to take care of the first two instances, and I'll let you get rid of the "nearest logic" for the cursor thing if you judge it's right to do so (I think it is).

2021-01-09 10:12 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        if (hoveredInteractables.Count > 0 && hoveredInteractables[0].playerId != playerId && hoveredInteractables[0].playerId != -1)
I think I'd rather this method take an Interactable, it makes more sense and is less cluttered to me to say `IsEnemy(otherInteractable)` rather than `IsEnemy(otherInteractable.PlayerId)`. Lmk if you disagree.

2021-01-09 11:10 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
The steps in both the Fighter and the Worker class are: 
1. Finding the Interactables around the unit's position (Unity-handled)
2. Casting those interactables to a specified type (O(n))
3. Finding the nearest one (O(n))

Now, the current implementation of these steps in the worker class combine steps 2 and 3 in one single loop. Therefore, if I make a method which finds the interactables nearby and casts them, and then use it in the Worker class, I'll have to add another pass of a for loop to find the closest one. That would take an algorithm that does 1 unity-handled operation + 1 for loop and turn it into 1 unity-handled operation, and then 2 for loops. Essentially, my point is that I like that the current method in the Worker class computes the nearest one and casts at the same time. Therefore, I think the right thing to do here is fo me to make a method which makes the current method of the worker class generic, and use it in both the Fighter and the Worker class. Therefore, we're keeping the algorithm at 1 unity-handled operation + 1 for loop for all 3 steps. 

Let me know if you think this makes sense, or if I missed something.

2021-01-09 14:48 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
Update: this is all great, but we forgot that fighters also need to check whether a specific interactable is an enemy or not. I'll try to find a good solution.

2021-01-09 19:23 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Fighter.cs
> +        List<Interactable> interactablesInAutoAttackRadius = Physics2D.OverlapCircleAll(transform.position, autoAttackRadius).Select(collider => collider.gameObject.GetComponent<Interactable>()).Wher
I didn't really manage to find a good solution, sadly. Feel free to give it a try. I still made a generic method called GetNearestIfAround<T>, which is used by the ResourceDrop, and will perhaps come in handy in the future. The Fighter class still uses the old way, for now...

2021-01-09 19:24 UTC, jpabadir commented
I couldn't figure out how to assign the hover and select indicators to the fighter using the new changes you made. Can you help me?

2021-01-09 20:20 UTC, jpabadir commented
Also, I think the bug in the selection is still here, and I think it was merged to master, because it came up when I was testing in this branch (in which I merged master). 

<img width="770" alt="Screen Shot 2021-01-09 at 9 17 12 PM" src="https://user-images.githubusercontent.com/21204917/104107880-4c2abd80-52c0-11eb-838a-a13b1fab0ede.png">

2021-01-17 23:29 UTC, JadenBalogh approved these changes
Changes look good, and game seems to function well.

2021-01-18 01:05 UTC, jpabadir reviewed
I would approve if I could, but this is technically my PR, so I can't. 

This looks great, nice work on the Utils class and its usages!

2021-01-18 01:05 UTC, jpabadir commented on Assets/Scripts/Game/Shared/Utils.cs
> +    }
Do we put a space between methods, or no because they have the same modifiers?

2021-01-18 01:05 UTC, jpabadir commented on Assets/Scripts/Game/Shared/Utils.cs
> +            if (pool[i].TryGetComponent<T>(out T t) && matchCondition(t))
Very cool!

2021-01-18 01:06 UTC, jpabadir commented
I see you approved. I'm merging! 🎉

2021-01-18 01:06 UTC, merged

2021-01-18 01:11 UTC, JadenBalogh commented on Assets/Scripts/Game/Shared/Utils.cs
> +    }
I decided to remove the space because I think it's a good way to quickly identify overloads vs. separate functions. Open to discussion on that front.

2021-01-18 01:12 UTC, jpabadir commented on Assets/Scripts/Game/Shared/Utils.cs
> +    }
Oh, so no spaces for overloads, bur spaces for other methods. Yep, fair enough!