Network spawaned workers
john-and-jaden/strategy.io pull request #65
Opened 2021-04-27 16:10 UTC by jpabadir

2021-04-27 17:44 UTC, jpabadir commented on Assets/Scripts/Game/System/BuildingSystem.cs
> +
😳

2021-04-27 18:06 UTC, jpabadir commented on Assets/Scripts/Game/Entity/Interactable.cs
> +
Necessary as RPCs must return void (or it gets more complex).

2021-07-14 02:00 UTC, JadenBalogh requested changes
Minor changes and cleanup needed, but otherwise looks awesome! Plays pretty much perfectly in client. 👌

2021-07-14 02:32 UTC, JadenBalogh approved these changes

2021-07-15 01:03 UTC, merged